import tsParser from '@typescript-eslint/parser'
import tsPlugin from '@typescript-eslint/eslint-plugin'

export default [
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/coverage/**',
      '**/.next/**',
      '**/.turbo/**',
      '**/*.tsbuildinfo',
      '**/next-env.d.ts', // generated by Next.js; not hand-edited or linted
      '.claude/worktrees/**', // transient agent worktrees (isolated builds); not source
      '.agents/**', // vendored third-party agent-skills (skills-lock.json); not our source
    ],
  },
  {
    files: ['**/*.{ts,tsx,mts,cts}'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 2022,
        sourceType: 'module',
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
    },
    rules: {
      ...tsPlugin.configs.recommended.rules,
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/explicit-module-boundary-types': 'error',
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },
  {
    // The legal-demo Next.js app: its public surface is React components, pages,
    // and route handlers, not a published library API. explicit-module-boundary-types
    // is meant for library boundaries (enforced on packages/*, where there are zero
    // violations) and is noise on app components — scoped off here only.
    files: ['apps/legal-demo/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/explicit-module-boundary-types': 'off',
    },
  },
]
