'use client'

import { useCallback, useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import Link from 'next/link'
import { callAttorneyMcp } from '@/lib/mcpAttorney'

// The exact field types the public booking page (apps/legal-demo/app/book)
// renders. Keep in lockstep with KNOWN_FIELD_TYPES in the legal API — anything
// else is rejected on save. The attorney picks by friendly label; the raw type
// key is never shown (WP2.4: no typed enums on the surface).
const FIELD_TYPES = [
  'text',
  'textarea',
  'select',
  'date',
  'number',
  'address_autocomplete',
  'members_repeater',
] as const
type FieldType = (typeof FIELD_TYPES)[number]

const FIELD_TYPE_LABELS: Record<FieldType, string> = {
  text: 'Short text',
  textarea: 'Long text',
  select: 'Dropdown',
  date: 'Date',
  number: 'Number',
  address_autocomplete: 'Address',
  members_repeater: 'Members (repeating)',
}

interface EditorField {
  // Stable internal id. Hidden from the UI; autogenerated from the label on save
  // for new fields and preserved for existing ones (so template bindings to a
  // field id survive a label change). Never shown or edited (Contract I).
  id: string
  label: string
  type: FieldType
  required: boolean
  allow_unknown: boolean
  ask_attorney: boolean
  // select
  options: string[]
  // members_repeater
  memberFields: EditorField[]
  minItems: number
}

interface EditorSection {
  id: string
  title: string
  fields: EditorField[]
}

interface EditorDoc {
  id: string
  version: number
  title: string
  jurisdiction: string
  sections: EditorSection[]
}

// What the API/MCP returns/accepts (the FIXED schema contract). No `help` is ever
// written; no form `description` is ever written (WP2.4).
interface WireField {
  id: string
  label: string
  type: string
  required?: boolean
  allow_unknown?: boolean
  ask_attorney?: boolean
  options?: string[]
  memberFields?: WireField[]
  minItems?: number
}
interface WireSection {
  id: string
  title: string
  fields: WireField[]
}
interface WireDoc {
  id: string
  version: number
  title: string
  jurisdiction?: string
  sections: WireSection[]
}

function isFieldType(t: string): t is FieldType {
  return (FIELD_TYPES as readonly string[]).includes(t)
}

// Slug from a human label, e.g. "Proposed LLC name" → "proposed_llc_name".
function slugify(s: string): string {
  return s
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 60)
}

// Reserve a unique id within `used`, falling back to a base and numeric suffix.
function uniqueId(preferred: string, fallback: string, used: Set<string>): string {
  const base = preferred || fallback || 'field'
  let id = base
  let n = 2
  while (used.has(id)) id = `${base}_${n++}`
  used.add(id)
  return id
}

function wireFieldToEditor(f: WireField): EditorField {
  return {
    id: f.id,
    label: f.label,
    // An unknown legacy type surfaces as Short text so the attorney can re-pick a
    // supported type before saving. Legacy `help` is intentionally dropped.
    type: isFieldType(f.type) ? f.type : 'text',
    required: f.required ?? false,
    allow_unknown: f.allow_unknown ?? false,
    ask_attorney: f.ask_attorney ?? false,
    options: Array.isArray(f.options) ? f.options : [],
    memberFields: Array.isArray(f.memberFields) ? f.memberFields.map(wireFieldToEditor) : [],
    minItems: typeof f.minItems === 'number' ? f.minItems : 1,
  }
}

function wireToEditor(doc: WireDoc): EditorDoc {
  return {
    id: doc.id,
    version: doc.version,
    title: doc.title ?? '',
    jurisdiction: doc.jurisdiction ?? '',
    sections: (doc.sections ?? []).map((s) => ({
      id: s.id,
      title: s.title,
      fields: (s.fields ?? []).map(wireFieldToEditor),
    })),
  }
}

// Editor → wire. Assigns a stable id (existing kept, new slugged from the label)
// and carries only the humane-intake flags + type-specific extras. No help, no
// description.
function editorFieldToWire(f: EditorField, used: Set<string>): WireField {
  const out: WireField = {
    id: uniqueId(f.id.trim(), slugify(f.label), used),
    label: f.label.trim(),
    type: f.type,
  }
  if (f.required) out.required = true
  if (f.allow_unknown) out.allow_unknown = true
  if (f.ask_attorney) out.ask_attorney = true
  if (f.type === 'select') out.options = f.options.map((o) => o.trim()).filter(Boolean)
  if (f.type === 'members_repeater') {
    const memberUsed = new Set<string>()
    out.memberFields = f.memberFields.map((mf) => editorFieldToWire(mf, memberUsed))
    out.minItems = f.minItems
  }
  return out
}

function editorToWire(doc: EditorDoc): WireDoc {
  const fieldIds = new Set<string>()
  const sectionIds = new Set<string>()
  return {
    id: doc.id,
    version: doc.version,
    title: doc.title.trim(),
    ...(doc.jurisdiction.trim() ? { jurisdiction: doc.jurisdiction.trim() } : {}),
    sections: doc.sections.map((s) => ({
      id: uniqueId(s.id.trim(), slugify(s.title), sectionIds),
      title: s.title.trim(),
      fields: s.fields.map((f) => editorFieldToWire(f, fieldIds)),
    })),
  }
}

function emptyField(): EditorField {
  return {
    id: '',
    label: '',
    type: 'text',
    required: false,
    allow_unknown: false,
    ask_attorney: false,
    options: [],
    memberFields: [],
    minItems: 1,
  }
}

function emptySection(): EditorSection {
  return { id: '', title: '', fields: [emptyField()] }
}

// Move the item at `from` to `to`, returning a new array.
function moveTo<T>(arr: T[], from: number, to: number): T[] {
  if (from === to || from < 0 || to < 0 || from >= arr.length || to >= arr.length) return arr
  const copy = [...arr]
  const [item] = copy.splice(from, 1)
  copy.splice(to, 0, item)
  return copy
}

export default function QuestionnaireEditorPage() {
  const params = useParams<{ serviceKey: string }>()
  const serviceKey = params.serviceKey

  const [doc, setDoc] = useState<EditorDoc | null>(null)
  const [empty, setEmpty] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)
  const [saved, setSaved] = useState(false)
  // Drag-to-reorder context: which section, and (for a field) which field index.
  const [drag, setDrag] = useState<{ si: number; fi: number | null } | null>(null)

  const load = useCallback(async () => {
    setError(null)
    try {
      const r = await callAttorneyMcp<{ questionnaire: WireDoc | null }>({
        toolName: 'legal.service.questionnaire.get',
        input: { serviceKey },
      })
      if (!r.questionnaire) {
        setEmpty(true)
        setDoc({
          id: serviceKey,
          version: 1,
          title: '',
          jurisdiction: '',
          sections: [emptySection()],
        })
        return
      }
      setEmpty(false)
      setDoc(wireToEditor(r.questionnaire))
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e))
    }
  }, [serviceKey])

  useEffect(() => {
    load()
  }, [load])

  function patch(mut: (d: EditorDoc) => EditorDoc) {
    setDoc((d) => (d ? mut(d) : d))
    setSaved(false)
  }
  function patchSection(si: number, mut: (s: EditorSection) => EditorSection) {
    patch((d) => ({ ...d, sections: d.sections.map((s, i) => (i === si ? mut(s) : s)) }))
  }
  function patchField(si: number, fi: number, mut: (f: EditorField) => EditorField) {
    patchSection(si, (s) => ({ ...s, fields: s.fields.map((f, i) => (i === fi ? mut(f) : f)) }))
  }

  async function save() {
    if (!doc) return
    setBusy(true)
    setError(null)
    try {
      const wire = editorToWire(doc)
      await callAttorneyMcp({
        toolName: 'legal.service.questionnaire.update',
        input: { serviceKey, intakeSchema: wire },
      })
      setSaved(true)
      setTimeout(() => setSaved(false), 2500)
      await load()
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e))
    } finally {
      setBusy(false)
    }
  }

  return (
    <main>
      <div
        className="attorney-page-head"
        style={{ display: 'flex', alignItems: 'center', gap: '0.7rem' }}
      >
        <h1 style={{ margin: 0 }}>Edit questionnaire</h1>
        <Link
          href={`/attorney/services/${serviceKey}`}
          className="back-link"
          style={{ marginLeft: 'auto' }}
        >
          Back to service
        </Link>
        <button className="primary" onClick={save} disabled={busy || !doc}>
          {busy ? 'Saving…' : 'Save new version'}
        </button>
      </div>

      <p style={{ color: 'var(--muted)', marginTop: '-0.4rem' }}>
        The intake form clients fill out when they book this service. Saving creates a new immutable
        version; the booking page picks it up immediately.
        {empty && ' No saved form yet — this starts from the bound default.'}
      </p>

      {error && <div className="alert alert-error">{error}</div>}
      {saved && (
        <div
          className="alert"
          style={{ background: 'var(--ok-soft)', color: '#166534', border: '1px solid #86efac' }}
        >
          Saved a new version.
        </div>
      )}

      {!doc ? (
        <div className="loading-block">
          <span className="spinner" /> Loading…
        </div>
      ) : (
        <>
          <section>
            <div className="form-grid">
              <label>
                <span>Form title</span>
                <input
                  value={doc.title}
                  onChange={(e) => patch((d) => ({ ...d, title: e.target.value }))}
                  placeholder="e.g. NC LLC operating agreement intake"
                />
              </label>
              <label>
                <span>Jurisdiction</span>
                <input
                  value={doc.jurisdiction}
                  onChange={(e) => patch((d) => ({ ...d, jurisdiction: e.target.value }))}
                  placeholder="e.g. NC"
                />
              </label>
            </div>
          </section>

          {doc.sections.map((section, si) => (
            <section
              key={si}
              style={{ borderLeft: '3px solid var(--border)' }}
              onDragOver={(e) => {
                if (drag && drag.fi === null) e.preventDefault()
              }}
              onDrop={() => {
                if (drag && drag.fi === null && drag.si !== si) {
                  patch((d) => ({ ...d, sections: moveTo(d.sections, drag.si, si) }))
                }
                setDrag(null)
              }}
            >
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: '0.5rem',
                  marginBottom: '0.6rem',
                }}
              >
                <span
                  className="qb-grip"
                  draggable
                  onDragStart={() => setDrag({ si, fi: null })}
                  onDragEnd={() => setDrag(null)}
                  title="Drag to reorder section"
                  aria-hidden
                >
                  ⠿
                </span>
                <strong>Section {si + 1}</strong>
                <span style={{ marginLeft: 'auto', display: 'flex', gap: '0.35rem' }}>
                  <button
                    onClick={() =>
                      patch((d) => ({ ...d, sections: moveTo(d.sections, si, si - 1) }))
                    }
                    disabled={si === 0}
                    title="Move up"
                  >
                    ↑
                  </button>
                  <button
                    onClick={() =>
                      patch((d) => ({ ...d, sections: moveTo(d.sections, si, si + 1) }))
                    }
                    disabled={si === doc.sections.length - 1}
                    title="Move down"
                  >
                    ↓
                  </button>
                  <button
                    className="danger outline"
                    onClick={() =>
                      patch((d) => ({ ...d, sections: d.sections.filter((_, i) => i !== si) }))
                    }
                  >
                    Remove section
                  </button>
                </span>
              </div>
              <label>
                <span>Section title</span>
                <input
                  value={section.title}
                  onChange={(e) => patchSection(si, (s) => ({ ...s, title: e.target.value }))}
                  placeholder="e.g. About the company"
                />
              </label>

              {section.fields.map((field, fi) => (
                <FieldEditor
                  key={fi}
                  field={field}
                  index={fi}
                  count={section.fields.length}
                  draggable
                  onDragStart={() => setDrag({ si, fi })}
                  onDragEnd={() => setDrag(null)}
                  onDropField={() => {
                    if (drag && drag.fi !== null && drag.si === si && drag.fi !== fi) {
                      patchSection(si, (s) => ({
                        ...s,
                        fields: moveTo(s.fields, drag.fi as number, fi),
                      }))
                    }
                    setDrag(null)
                  }}
                  dragActive={!!drag && drag.fi !== null && drag.si === si}
                  onChange={(mut) => patchField(si, fi, mut)}
                  onMove={(delta) =>
                    patchSection(si, (s) => ({ ...s, fields: moveTo(s.fields, fi, fi + delta) }))
                  }
                  onRemove={() =>
                    patchSection(si, (s) => ({ ...s, fields: s.fields.filter((_, i) => i !== fi) }))
                  }
                />
              ))}

              <button
                onClick={() =>
                  patchSection(si, (s) => ({ ...s, fields: [...s.fields, emptyField()] }))
                }
              >
                + Add question
              </button>
            </section>
          ))}

          <button
            onClick={() => patch((d) => ({ ...d, sections: [...d.sections, emptySection()] }))}
          >
            + Add section
          </button>
        </>
      )}
    </main>
  )
}

function OptionPills({
  options,
  onChange,
}: {
  options: string[]
  onChange: (next: string[]) => void
}) {
  const [draft, setDraft] = useState('')
  const add = () => {
    const v = draft.trim()
    if (!v || options.includes(v)) return setDraft('')
    onChange([...options, v])
    setDraft('')
  }
  return (
    <div>
      <span style={{ fontSize: '0.85rem', fontWeight: 600 }}>Choices</span>
      <div className="qb-pills">
        {options.map((opt, i) => (
          <span key={i} className="qb-pill">
            {opt}
            <button
              type="button"
              title="Remove choice"
              onClick={() => onChange(options.filter((_, j) => j !== i))}
            >
              ×
            </button>
          </span>
        ))}
        {options.length === 0 && (
          <span style={{ color: 'var(--muted)', fontSize: '0.85rem' }}>No choices yet</span>
        )}
      </div>
      <div className="qb-pill-add">
        <input
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === 'Enter') {
              e.preventDefault()
              add()
            }
          }}
          placeholder="Add a choice and press Enter"
        />
        <button type="button" onClick={add}>
          Add
        </button>
      </div>
    </div>
  )
}

function FieldEditor({
  field,
  index,
  count,
  onChange,
  onMove,
  onRemove,
  draggable,
  onDragStart,
  onDragEnd,
  onDropField,
  dragActive,
}: {
  field: EditorField
  index: number
  count: number
  onChange: (mut: (f: EditorField) => EditorField) => void
  onMove: (delta: number) => void
  onRemove: () => void
  draggable?: boolean
  onDragStart?: () => void
  onDragEnd?: () => void
  onDropField?: () => void
  dragActive?: boolean
}) {
  return (
    <fieldset
      className="member-row"
      style={{ marginTop: '0.6rem' }}
      onDragOver={(e) => {
        if (dragActive) {
          e.preventDefault()
          e.stopPropagation()
        }
      }}
      onDrop={(e) => {
        if (onDropField) {
          e.stopPropagation()
          onDropField()
        }
      }}
    >
      <legend style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
        {draggable && (
          <span
            className="qb-grip"
            draggable
            onDragStart={(e) => {
              e.stopPropagation()
              onDragStart?.()
            }}
            onDragEnd={() => onDragEnd?.()}
            title="Drag to reorder question"
            aria-hidden
          >
            ⠿
          </span>
        )}
        Question {index + 1}
        <span style={{ marginLeft: '0.4rem', display: 'inline-flex', gap: '0.3rem' }}>
          <button onClick={() => onMove(-1)} disabled={index === 0} title="Move up">
            ↑
          </button>
          <button onClick={() => onMove(1)} disabled={index === count - 1} title="Move down">
            ↓
          </button>
          <button className="danger outline" onClick={onRemove}>
            Remove
          </button>
        </span>
      </legend>
      <div className="form-grid">
        <label>
          <span>Question</span>
          <input
            value={field.label}
            onChange={(e) => onChange((f) => ({ ...f, label: e.target.value }))}
            placeholder="e.g. Proposed LLC name"
          />
        </label>
        <label>
          <span>Answer type</span>
          <select
            value={field.type}
            onChange={(e) => onChange((f) => ({ ...f, type: e.target.value as FieldType }))}
          >
            {FIELD_TYPES.map((t) => (
              <option key={t} value={t}>
                {FIELD_TYPE_LABELS[t]}
              </option>
            ))}
          </select>
        </label>
      </div>

      <div className="qb-toggles">
        <label className="qb-toggle">
          <input
            type="checkbox"
            checked={field.required}
            onChange={(e) => onChange((f) => ({ ...f, required: e.target.checked }))}
          />
          <span>Required</span>
        </label>
        <label className="qb-toggle">
          <input
            type="checkbox"
            checked={field.allow_unknown}
            onChange={(e) => onChange((f) => ({ ...f, allow_unknown: e.target.checked }))}
          />
          <span>Allow “I don’t know”</span>
        </label>
        <label className="qb-toggle">
          <input
            type="checkbox"
            checked={field.ask_attorney}
            onChange={(e) => onChange((f) => ({ ...f, ask_attorney: e.target.checked }))}
          />
          <span>Flag for attorney follow-up</span>
        </label>
      </div>

      {field.type === 'select' && (
        <OptionPills
          options={field.options}
          onChange={(next) => onChange((f) => ({ ...f, options: next }))}
        />
      )}

      {field.type === 'members_repeater' && (
        <div style={{ marginTop: '0.5rem' }}>
          <label>
            <span>Minimum members</span>
            <input
              type="number"
              inputMode="numeric"
              min={0}
              value={field.minItems}
              onChange={(e) => onChange((f) => ({ ...f, minItems: Number(e.target.value) || 0 }))}
            />
          </label>
          <div style={{ fontWeight: 600, margin: '0.5rem 0 0.3rem' }}>Per-member questions</div>
          {field.memberFields.map((mf, mi) => (
            <FieldEditor
              key={mi}
              field={mf}
              index={mi}
              count={field.memberFields.length}
              onChange={(mut) =>
                onChange((f) => ({
                  ...f,
                  memberFields: f.memberFields.map((x, i) => (i === mi ? mut(x) : x)),
                }))
              }
              onMove={(delta) =>
                onChange((f) => ({ ...f, memberFields: moveTo(f.memberFields, mi, mi + delta) }))
              }
              onRemove={() =>
                onChange((f) => ({
                  ...f,
                  memberFields: f.memberFields.filter((_, i) => i !== mi),
                }))
              }
            />
          ))}
          <button
            onClick={() =>
              onChange((f) => ({ ...f, memberFields: [...f.memberFields, emptyField()] }))
            }
          >
            + Add per-member question
          </button>
        </div>
      )}
    </fieldset>
  )
}
