// Contract H — deterministic template merge. NO AI, pure, side-effect-free.
//
// A template body is markdown/text containing {{token}} markers. Each token is a
// BINDING to a questionnaire field by id (the WP2.4 autogenerated slug, e.g.
// {{company_name}}). Rendering a document is just substitution: each {{token}} is
// replaced by answers[token]; a token with no answer is reported in missingFields
// (and left as a visible [[token]] placeholder so gaps are obvious, never silent).
//
// Composition (templates within templates): {{>other_template_key}} inlines
// another template's body, resolved from the `includes` map, to a bounded depth.
// This is the seam for nesting; single level works today, deeper nesting is
// bounded by maxIncludeDepth (see TEMPLATES.md / the WP2.5 report).

const TOKEN_RE = /\{\{\s*([a-z0-9_]+)\s*\}\}/gi
const INCLUDE_RE = /\{\{\s*>\s*([a-z0-9_]+)\s*\}\}/gi

export interface RenderResult {
  // The merged document, HTML-escaped and safe to inject (render with
  // white-space: pre-wrap). Deterministic: same inputs → same output.
  html: string
  // Token ids that were filled from an answer / that had no usable answer.
  filledFields: string[]
  missingFields: string[]
}

export interface RenderOptions {
  // template_key → body, for {{>key}} composition.
  includes?: Record<string, string>
  maxIncludeDepth?: number
}

// The WP2.4 "I don't know" sentinel — counts as unanswered for drafting.
const UNKNOWN_ANSWER = '__unknown__'

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

// The distinct input tokens (field bindings) in a body, in first-seen order.
// Excludes {{>includes}}.
export function extractInputTokens(body: string): string[] {
  const withoutIncludes = body.replace(INCLUDE_RE, '')
  const seen = new Set<string>()
  const out: string[] = []
  for (const m of withoutIncludes.matchAll(TOKEN_RE)) {
    const tok = m[1]?.toLowerCase()
    if (tok && !seen.has(tok)) {
      seen.add(tok)
      out.push(tok)
    }
  }
  return out
}

// Every token the MERGE RENDERER (templateMerge.ts) would try to fill — the same
// `{{ token }}` shape but also matching DOTTED paths like `{{member.0.name}}`.
// extractInputTokens above is the flat-only set; this is the renderer-complete set.
// The build-wizard's variable-contract check uses THIS so a dotted token — which the
// flat answer map can never fill, so it renders [[MISSING]] at merge time — is SEEN
// and flagged as an orphan instead of slipping silently past the flat extractor.
// (Excludes {{>includes}}; first-seen order; lower-cased like the renderer matches.)
export function extractRenderedTokens(body: string): string[] {
  const withoutIncludes = body.replace(INCLUDE_RE, '')
  const seen = new Set<string>()
  const out: string[] = []
  for (const m of withoutIncludes.matchAll(/\{\{\s*([a-zA-Z0-9_.]+)\s*\}\}/g)) {
    const tok = m[1]?.toLowerCase()
    if (tok && !seen.has(tok)) {
      seen.add(tok)
      out.push(tok)
    }
  }
  return out
}

// The {{>include}} template keys referenced by a body (first-seen order).
export function extractIncludeKeys(body: string): string[] {
  const seen = new Set<string>()
  const out: string[] = []
  for (const m of body.matchAll(INCLUDE_RE)) {
    const key = m[1]?.toLowerCase()
    if (key && !seen.has(key)) {
      seen.add(key)
      out.push(key)
    }
  }
  return out
}

function resolveIncludes(body: string, opts: RenderOptions): string {
  const maxDepth = opts.maxIncludeDepth ?? 3
  let resolved = body
  for (let depth = 0; depth < maxDepth; depth++) {
    if (!INCLUDE_RE.test(resolved)) break
    INCLUDE_RE.lastIndex = 0
    resolved = resolved.replace(INCLUDE_RE, (_m, key: string) => {
      const inc = opts.includes?.[key.toLowerCase()]
      return inc ?? `[[MISSING TEMPLATE: ${key}]]`
    })
  }
  return resolved
}

// Render a template body by substituting questionnaire answers into its {{tokens}}.
export function renderTemplate(
  body: string,
  answers: Record<string, unknown>,
  opts: RenderOptions = {},
): RenderResult {
  const resolved = resolveIncludes(body, opts)
  const filled = new Set<string>()
  const missing = new Set<string>()

  const html = escapeHtml(resolved).replace(TOKEN_RE, (_m, rawToken: string) => {
    const token = rawToken.toLowerCase()
    const v = answers[token]
    if (v === undefined || v === null || v === '' || v === UNKNOWN_ANSWER) {
      missing.add(token)
      return v === UNKNOWN_ANSWER ? `[[${token}: client doesn’t know]]` : `[[${token}]]`
    }
    filled.add(token)
    return escapeHtml(String(v))
  })

  return { html, filledFields: [...filled], missingFields: [...missing] }
}

// Humanize a token/field id into a question label: company_name → "Company name".
export function humanizeToken(token: string): string {
  const s = token.replace(/_/g, ' ').trim()
  return s ? s.charAt(0).toUpperCase() + s.slice(1) : token
}

// Auto-generate a Contract-I questionnaire (intake_schema shape) from a template's
// {{inputs}} — one question per bound token, so every token has a question (no
// orphans). Section ids/field ids are the token ids themselves, keeping the merge
// binding exact.
export function questionnaireFromTemplate(
  templateName: string,
  body: string,
): {
  title: string
  sections: Array<{
    id: string
    title: string
    fields: Array<{ id: string; label: string; type: 'text'; required: boolean }>
  }>
} {
  const tokens = extractInputTokens(body)
  return {
    title: `${templateName} — intake`.trim(),
    sections: [
      {
        id: 'document_fields',
        title: 'Document fields',
        fields: tokens.map((tok) => ({
          id: tok,
          label: humanizeToken(tok),
          type: 'text' as const,
          required: true,
        })),
      },
    ],
  }
}
