export * from './createMatter.js'
export * from './templateMerge.js'
export * from './submitQuestionnaire.js'
export * from './recordManualCall.js'
export * from './loadCall.js'
export * from './generateDraft.js'
export * from './cacheDraft.js'
export * from './reviewDraft.js'
export * from './services.js'
export * from './calendar.js'
export * from './google.js'
export * from './granola.js'
export * from './identity.js'
export * from './clientIdentity.js'
export * from './partners.js'
export * from './tenantSettings.js'
export * from './firmSignature.js'
export * from './firmBookingRules.js'
export * from './integrations.js'
export * from './granolaIngestion.js'
export * from './granolaImport.js'
export * from './notifications.js'
export * from './calendarWorkspace.js'
export * from './mailWorkspace.js'
export * from './clientMessaging.js'
export * from './notificationTemplates.js'
export * from './templatesCatalog.js'
export * from './standaloneTemplates.js'
export * from './questionnaireLibrary.js'
export * from './questionTemplate.js'
export * from './importPdf.js'
export * from './email.js'
export * from './research.js'
export * from './assistant.js'
export * from './assistantModels.js'
export * from './assistantContext.js'
export * from './assistantChat.js'
export * from './feedbackNotifications.js'
export * from './timeExpense.js'
export * from './billing.js'
export * from './rates.js'
export * from './savedViews.js'
export * from './meetings.js'
export * from './esign.js'
export * from './users.js'
export { getStubAvailability, mergeBusyIntervals } from '../adapters/googleCalendar.js'
export type { AvailabilitySlot, CreatedEvent, BusyInterval } from '../adapters/googleCalendar.js'
// `generateDraft.ts` and `services.ts` both define an identical `GenerationMode`
// alias, so the wildcard re-exports above leave it ambiguous (TS2308) the moment
// this barrel's declarations are re-emitted. Pin the canonical source explicitly
// (TS's own resolution hint); an explicit named re-export wins over the stars.
export type { GenerationMode } from './generateDraft.js'
