// Mail workspace (WP7, REQ-CALMAIL-02/03): client-related Gmail in-app —
// read, reply, compose — with every send through mail.send (provenance
// integration:gmail) and inbound mail ingested idempotently via mail.ingest.
// SCOPE DISCIPLINE: every Gmail query is constrained to known matter-contact
// addresses; unrelated personal/firm mail is never fetched or stored.
import {
  submitAction,
  withActionContext,
  type ActionContext,
  type ActionResult,
} from '@exsto/substrate'
import {
  listClientThreads,
  getClientThread,
  sendEmail,
  type GmailThreadSummary,
  type GmailThreadDetail,
  type EmailAttachment,
} from '../adapters/gmail.js'
import { resolveEmailSignature } from './firmSignature.js'
import { authorizedSendMatters, getMatterAccess } from './matterAccess.js'
import { resolveMatterAttachments, type AttachmentRef } from './mailAttachments.js'
import { getConnectionInfo, resolveFirmPrimaryActor } from '../adapters/connectionStore.js'

// True iff this actor has a 'connected' Google account with the gmail.send scope —
// i.e. an outbound email can actually be sent from their mailbox.
async function canSendAsActor(
  tenantId: string,
  actorId: string | null | undefined,
): Promise<boolean> {
  if (!actorId) return false
  const info = await getConnectionInfo(tenantId, 'google', actorId)
  return !!info && info.status === 'connected' && (info.scope ?? '').includes('gmail.send')
}

// Resolve the actor whose Gmail an outbound client email sends FROM. Beta feedback:
// "everything should come from the executor's email" — so prefer the matter OWNER
// (the responsible attorney), then the actual sender, then the firm-primary. Each
// candidate must actually have a usable Gmail send connection; the matter owner is
// not always connected (e.g. a practicing attorney who hasn't linked Gmail yet), so
// this degrades gracefully instead of hard-failing the send. Falls back to
// ctx.actorId if nobody is connected (sendEmail then surfaces a clear connect error).
export async function resolveSendAsActor(
  ctx: ActionContext,
  matterEntityId: string | null,
): Promise<string> {
  const ownerActorId = matterEntityId
    ? (await getMatterAccess(ctx, matterEntityId)).ownerActorId
    : null
  const firmPrimary = await resolveFirmPrimaryActor(ctx.tenantId, 'google')
  for (const candidate of [ownerActorId, ctx.actorId, firmPrimary]) {
    if (await canSendAsActor(ctx.tenantId, candidate)) return candidate!
  }
  return ctx.actorId
}

// Build the outbound attachment list for a send authorized on `matterEntityId`:
// resolve client document REFERENCES to bytes (scope-checked against THIS matter)
// and append trusted server-generated bytes. This keeps the doc∈matter check in the
// core, bound to the same matter the recipient/sender authz used.
async function buildSendAttachments(
  ctx: ActionContext,
  matterEntityId: string,
  input: {
    attachmentRefs?: AttachmentRef[]
    downloadUpload?: (objectKey: string) => Promise<Buffer>
    systemAttachments?: EmailAttachment[]
  },
): Promise<EmailAttachment[] | undefined> {
  const refs = input.attachmentRefs ?? []
  const resolved = refs.length
    ? await resolveMatterAttachments(ctx, {
        matterEntityId,
        refs,
        downloadUpload:
          input.downloadUpload ??
          (() => {
            throw new Error('An attachment byte resolver is required to attach uploaded files.')
          }),
      })
    : []
  const all = [...resolved, ...(input.systemAttachments ?? [])]
  return all.length ? all : undefined
}

// ── Signature (fix #10) ──────────────────────────────────────────────────────
// Append the firm signature to a message body (and its HTML alternative, if
// present). Applied centrally here so EVERY outbound client send — manual
// compose, replies, booking confirmations (S5), invoice emails (S7) — inherits
// it without the caller reimplementing it. Resolution (stored vs firm-derived
// default vs disabled) lives in resolveEmailSignature; '' means append nothing.
function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

export function withSignature(
  parts: { body: string; html?: string },
  signature: string,
): { body: string; html?: string } {
  const sig = signature.trim()
  if (!sig) return parts
  // Standard "-- " delimiter so clients recognise it as a signature block.
  const body = `${parts.body.replace(/\s+$/, '')}\n\n-- \n${sig}\n`
  let html = parts.html
  if (html) {
    const sigHtml = `<br><br><div class="firm-signature" style="color:#555">--<br>${escapeHtml(
      sig,
    ).replace(/\n/g, '<br>')}</div>`
    html = /<\/body\s*>/i.test(html)
      ? html.replace(/<\/body\s*>/i, `${sigHtml}</body>`)
      : html + sigHtml
  }
  return { body, html }
}

// All client_contact emails with their matters (the allow-list that scopes
// every Gmail query).
async function clientEmailIndex(
  ctx: ActionContext,
): Promise<Map<string, Array<{ matterEntityId: string; matterNumber: string }>>> {
  return withActionContext(ctx, async (client) => {
    const res = await client.query<{
      email: string
      matter_id: string
      matter_number: string
    }>(
      `WITH latest_emails AS (
         SELECT DISTINCT ON (a.entity_id) a.entity_id, lower(a.value #>> '{}') AS email
         FROM attribute a
         JOIN attribute_kind_definition akd ON akd.id = a.attribute_kind_id
         JOIN entity e ON e.id = a.entity_id
         JOIN entity_kind_definition ekd ON ekd.id = e.entity_kind_id
         WHERE a.tenant_id = $1 AND akd.kind_name = 'email' AND ekd.kind_name = 'client_contact'
         ORDER BY a.entity_id, a.valid_from DESC
       )
       SELECT le.email, m.id AS matter_id, m.name AS matter_number
       FROM latest_emails le
       JOIN relationship r ON r.source_entity_id = le.entity_id
       JOIN relationship_kind_definition rkd ON rkd.id = r.relationship_kind_id AND rkd.kind_name = 'client_of'
       JOIN entity m ON m.id = r.target_entity_id
       WHERE m.tenant_id = $1 AND m.status = 'active'`,
      [ctx.tenantId],
    )
    const map = new Map<string, Array<{ matterEntityId: string; matterNumber: string }>>()
    for (const row of res.rows) {
      const list = map.get(row.email) ?? []
      list.push({ matterEntityId: row.matter_id, matterNumber: row.matter_number })
      map.set(row.email, list)
    }
    return map
  })
}

// All client_contact emails → display name (latest full_name). Lets the inbox
// label rows with the person's name instead of a raw address. Scope-matched to
// the same client_contact allow-list as clientEmailIndex.
async function clientNameIndex(ctx: ActionContext): Promise<Map<string, string>> {
  return withActionContext(ctx, async (client) => {
    const res = await client.query<{ email: string; full_name: string | null }>(
      `WITH latest_emails AS (
         SELECT DISTINCT ON (a.entity_id) a.entity_id, lower(a.value #>> '{}') AS email
         FROM attribute a
         JOIN attribute_kind_definition akd ON akd.id = a.attribute_kind_id
         JOIN entity e ON e.id = a.entity_id
         JOIN entity_kind_definition ekd ON ekd.id = e.entity_kind_id
         WHERE a.tenant_id = $1 AND akd.kind_name = 'email' AND ekd.kind_name = 'client_contact'
           AND e.status = 'active'
         ORDER BY a.entity_id, a.valid_from DESC
       ),
       latest_names AS (
         SELECT DISTINCT ON (a.entity_id) a.entity_id, a.value #>> '{}' AS full_name
         FROM attribute a
         JOIN attribute_kind_definition akd ON akd.id = a.attribute_kind_id
         WHERE a.tenant_id = $1 AND akd.kind_name = 'full_name'
         ORDER BY a.entity_id, a.valid_from DESC
       )
       SELECT le.email, ln.full_name
       FROM latest_emails le
       LEFT JOIN latest_names ln ON ln.entity_id = le.entity_id`,
      [ctx.tenantId],
    )
    const map = new Map<string, string>()
    for (const row of res.rows) {
      const name = row.full_name?.trim()
      if (name) map.set(row.email, name)
    }
    return map
  })
}

// Bare address out of "Name <a@b.com>" (or the string itself), lowercased — the
// key the name index uses.
function bareEmailKey(addr: string): string {
  const m = addr.match(/<([^>]+)>/)
  return (m ? m[1]! : addr).trim().toLowerCase()
}

// The subset of the name index that applies to this thread's participants, keyed
// by lowercased bare address. Kept per-thread so we never ship the firm's whole
// contact list to the client.
function namesForParticipants(
  participants: string[],
  names: Map<string, string>,
): Record<string, string> {
  const out: Record<string, string> = {}
  for (const p of participants) {
    const name = names.get(bareEmailKey(p))
    if (name) out[bareEmailKey(p)] = name
  }
  return out
}

export interface MailThreadSummary extends GmailThreadSummary {
  matters: Array<{ matterEntityId: string; matterNumber: string }>
  // email (lowercased, bare) → client contact display name, for known contacts.
  participantNames: Record<string, string>
}

export async function listMailThreads(
  ctx: ActionContext,
  search?: string,
): Promise<{
  threads: MailThreadSummary[]
  clientEmailCount: number
}> {
  const index = await clientEmailIndex(ctx)
  const emails = [...index.keys()].filter((e) => !e.endsWith('@example.test'))
  if (emails.length === 0) return { threads: [], clientEmailCount: 0 }
  const [threads, names] = await Promise.all([
    listClientThreads(ctx.tenantId, emails, 50, ctx.actorId, search),
    clientNameIndex(ctx),
  ])
  return {
    clientEmailCount: emails.length,
    threads: threads.map((t) => ({
      ...t,
      matters: dedupeMatters(t.participantEmails.flatMap((e) => index.get(e.toLowerCase()) ?? [])),
      participantNames: namesForParticipants(t.participantEmails, names),
    })),
  }
}

function dedupeMatters(
  list: Array<{ matterEntityId: string; matterNumber: string }>,
): Array<{ matterEntityId: string; matterNumber: string }> {
  const seen = new Map<string, { matterEntityId: string; matterNumber: string }>()
  for (const m of list) seen.set(m.matterEntityId, m)
  return [...seen.values()]
}

export interface MailThreadView extends GmailThreadDetail {
  matters: Array<{ matterEntityId: string; matterNumber: string }>
  // email (lowercased, bare) → client contact display name, for known contacts.
  participantNames: Record<string, string>
}

// Open a thread: live read from Gmail + idempotent ingestion into the
// substrate (mail.ingest), matter-matched by participant emails.
export async function openMailThread(
  ctx: ActionContext,
  gmailThreadId: string,
): Promise<MailThreadView> {
  const detail = await getClientThread(ctx.tenantId, gmailThreadId, ctx.actorId)
  const [index, names] = await Promise.all([clientEmailIndex(ctx), clientNameIndex(ctx)])
  const matters = dedupeMatters(
    detail.participantEmails.flatMap((e) => index.get(e.toLowerCase()) ?? []),
  )

  // Scope discipline: a thread with no known client participant is not ours
  // to store or display.
  if (matters.length === 0 && !detail.participantEmails.some((e) => index.has(e.toLowerCase()))) {
    throw new Error('Thread has no known client participant; not a client thread.')
  }

  await submitAction(ctx, {
    actionKindName: 'mail.ingest',
    intentKind: 'automatic_sync',
    payload: {
      gmail_thread_id: detail.gmailThreadId,
      subject: detail.subject,
      participant_emails: detail.participantEmails,
      matter_entity_id: matters[0]?.matterEntityId ?? null,
      messages: detail.messages.map((m) => ({
        gmail_message_id: m.gmailMessageId,
        from: m.from,
        to: m.to,
        sent_at: m.sentAt,
        body_text: m.bodyText,
      })),
    },
  })

  return {
    ...detail,
    matters,
    participantNames: namesForParticipants(detail.participantEmails, names),
  }
}

// The matters a recipient email is a client of — for the compose attachment picker
// (which matter's documents may be attached for this recipient). Empty if the
// address is not a known client contact.
export async function recipientMatters(
  ctx: ActionContext,
  email: string,
): Promise<Array<{ matterEntityId: string; matterNumber: string }>> {
  const index = await clientEmailIndex(ctx)
  return dedupeMatters(index.get(email.trim().toLowerCase()) ?? [])
}

export interface ReplyInput {
  gmailThreadId: string
  bodyText: string
  // Optional rich-text (HTML) alternative from the in-app composer. When present
  // the reply goes out multipart/alternative (formatted HTML + plaintext fallback);
  // bodyText stays the recorded body and the plaintext part. The firm signature is
  // appended to both centrally.
  bodyHtml?: string
  // Client-chosen document attachments, as REFERENCES — resolved to bytes HERE and
  // scope-checked against `matterId` (the matter this reply is authorized for).
  attachmentRefs?: AttachmentRef[]
  downloadUpload?: (objectKey: string) => Promise<Buffer>
  // Optional matter to attribute + scope the reply (and its attachments) to. Must be
  // one the recipient is a client of (and the sender may send on). Defaults to the
  // first authorized matter otherwise.
  matterId?: string
}

// Reply in-app: goes out through the attorney's real Gmail, recorded as a
// mail.send action with provenance integration:gmail.
export async function replyToThread(ctx: ActionContext, input: ReplyInput): Promise<ActionResult> {
  const detail = await getClientThread(ctx.tenantId, input.gmailThreadId, ctx.actorId)
  const index = await clientEmailIndex(ctx)
  const clientParticipant = detail.participantEmails.find((e) => index.has(e.toLowerCase()))
  if (!clientParticipant) {
    throw new Error('Refusing to reply: thread has no known client participant.')
  }
  // Send authz (0088): the reply goes to clientParticipant, so authorize the
  // sender against THAT recipient's matters specifically — NOT the union of every
  // participant's matters (a thread can mix clients from different matters; the
  // sender must be authorized on a matter the actual recipient belongs to). An
  // attorney may send only on matters they own, are granted, or as a firm admin.
  const recipientMatters = index.get(clientParticipant.toLowerCase()) ?? []
  const authorized = await authorizedSendMatters(
    ctx,
    recipientMatters.map((m) => m.matterEntityId),
  )
  if (authorized.length === 0) {
    throw new Error(
      'You are not authorized to send on this matter. Ask the matter owner or a firm admin for access.',
    )
  }
  // When a matter is specified (e.g. to scope attachments), it must be one the
  // recipient is a client of AND the sender may send on — never silently re-route.
  if (input.matterId && !authorized.includes(input.matterId)) {
    throw new Error(
      'You are not authorized to send on the specified matter for this recipient. Ask the matter owner or a firm admin for access.',
    )
  }
  const matterEntityId = input.matterId || authorized[0]!

  // Resolve client document refs to bytes HERE, scope-checked against matterEntityId.
  const attachments = await buildSendAttachments(ctx, matterEntityId, input)

  const last = detail.messages[detail.messages.length - 1]
  // Sign centrally — replies carry the firm signature too (fix #10). The HTML
  // alternative (when the composer sent one) is signed alongside the plaintext.
  const { body: signedBody, html: signedHtml } = withSignature(
    { body: input.bodyText, html: input.bodyHtml },
    await resolveEmailSignature(ctx),
  )
  // Send FROM the matter owner's mailbox when possible (beta feedback), else fall
  // back to the sender / firm-primary.
  const sendAsActor = await resolveSendAsActor(ctx, matterEntityId)
  const sent = await sendEmail(
    ctx.tenantId,
    {
      to: clientParticipant,
      subject: detail.subject.startsWith('Re:') ? detail.subject : `Re: ${detail.subject}`,
      body: signedBody,
      html: signedHtml,
      gmailThreadId: input.gmailThreadId,
      inReplyToMessageIdHeader: last?.messageIdHeader ?? undefined,
      attachments,
    },
    sendAsActor,
  )
  return submitAction(ctx, {
    actionKindName: 'mail.send',
    intentKind: 'enforcement',
    payload: {
      gmail_thread_id: input.gmailThreadId,
      gmail_message_id: sent.messageId,
      subject: detail.subject,
      to: clientParticipant,
      from: sent.from,
      body_text: signedBody,
      matter_entity_id: matterEntityId,
      participant_emails: detail.participantEmails,
      attachment_filenames: (attachments ?? []).map((a) => a.filename),
    },
  })
}

// ───────────────────────────────────────────────────────────────────────────
// Contract B — enqueueClientEmail. The ONE through-the-core send path for
// human-/system-composed client mail: it sends via the attorney's Gmail and
// records a mail.send action (provenance integration:gmail) so the message lands
// in the matter's communication history. Client-mail-scoped: the recipient must
// be a known client contact, same discipline as every other Mail-tab send.
//
// S4 (invoice emails) and S5 (signature-request emails) import this — keep the
// signature stable. Returns the action result plus the Gmail send details so
// callers that need the message id (draft links, receipts) can use them.
// ───────────────────────────────────────────────────────────────────────────

export interface EnqueueClientEmailInput {
  to: string
  subject: string
  body: string
  // Optional branded HTML alternative (text/html). Plaintext `body` is always the
  // fallback. Callers render it via the email kit (renderEmailHtml).
  html?: string
  // Optional explicit matter linkage. When omitted, resolved from the recipient's
  // client-contact → matter mapping (first matter).
  matterId?: string
  // Optional contact reference (carried for provenance; scoping is by `to`).
  contactId?: string
  // Client-chosen document attachments, as REFERENCES — resolved to bytes HERE,
  // scope-checked against the SAME matter this send is authorized for (so the
  // composite doc∈matter ∧ recipient client_of matter is enforced in the core, not
  // the adapter). `downloadUpload` injects the app-only Storage byte read.
  attachmentRefs?: AttachmentRef[]
  downloadUpload?: (objectKey: string) => Promise<Buffer>
  // Trusted, server-generated attachments (e.g. an invoice PDF) — NOT scope-checked
  // because the server produced them. Never populate this from client input.
  systemAttachments?: EmailAttachment[]
}

export interface EnqueueClientEmailResult {
  action: ActionResult
  messageId: string
  from: string
  to: string
}

export async function enqueueClientEmail(
  ctx: ActionContext,
  input: EnqueueClientEmailInput,
): Promise<EnqueueClientEmailResult> {
  const index = await clientEmailIndex(ctx)
  const matters = index.get(input.to.toLowerCase())
  if (!matters || matters.length === 0) {
    throw new Error(
      `Refusing to send: ${input.to} is not a known client contact (client-mail-only discipline).`,
    )
  }
  // Send authz (0088): authorize the sender on the recipient's matters BEFORE
  // sending, and attribute the message to a matter they may send on (preferring an
  // explicitly supplied one). An attorney may send only on matters they own, are
  // granted, or as a firm admin.
  const authorized = await authorizedSendMatters(
    ctx,
    matters.map((m) => m.matterEntityId),
  )
  if (authorized.length === 0) {
    throw new Error(
      'You are not authorized to send to this contact on any of their matters. Ask the matter owner or a firm admin for access.',
    )
  }
  // An explicit matter must be one the actor may send on — never silently re-route
  // an unauthorized matterId to a different (authorized) matter (provenance/intent).
  if (input.matterId && !authorized.includes(input.matterId)) {
    throw new Error(
      'You are not authorized to send on the specified matter for this contact. Ask the matter owner or a firm admin for access.',
    )
  }
  const matterEntityId = input.matterId || authorized[0]!

  // Resolve client document refs to bytes HERE, scope-checked against matterEntityId
  // (the matter this send is authorized for), then append trusted server bytes.
  const attachments = await buildSendAttachments(ctx, matterEntityId, input)

  // Sign centrally: every Contract B send carries the firm signature (fix #10).
  const signed = withSignature(
    { body: input.body, html: input.html },
    await resolveEmailSignature(ctx),
  )
  // Send FROM the matter owner's mailbox when possible (beta feedback), else fall
  // back to the sender / firm-primary.
  const sendAsActor = await resolveSendAsActor(ctx, matterEntityId)
  const sent = await sendEmail(
    ctx.tenantId,
    {
      to: input.to,
      subject: input.subject,
      body: signed.body,
      html: signed.html,
      attachments,
    },
    sendAsActor,
  )

  const action = await submitAction(ctx, {
    actionKindName: 'mail.send',
    intentKind: 'enforcement',
    payload: {
      gmail_thread_id: null,
      gmail_message_id: sent.messageId,
      subject: input.subject,
      to: input.to,
      from: sent.from,
      body_text: signed.body,
      matter_entity_id: matterEntityId,
      contact_entity_id: input.contactId ?? null,
      participant_emails: [input.to, sent.from],
      attachment_filenames: (attachments ?? []).map((a) => a.filename),
    },
  })

  return { action, messageId: sent.messageId, from: sent.from, to: input.to }
}

export interface ComposeInput {
  to: string
  subject: string
  bodyText: string
  // Optional rich-text (HTML) alternative from the in-app composer (see ReplyInput).
  bodyHtml?: string
}

// Mail-tab compose, kept as the thin UI-facing wrapper over Contract B.
export async function composeToClient(
  ctx: ActionContext,
  input: ComposeInput,
): Promise<ActionResult> {
  const { action } = await enqueueClientEmail(ctx, {
    to: input.to,
    subject: input.subject,
    body: input.bodyText,
    html: input.bodyHtml,
  })
  return action
}

export interface MatterCommunication {
  threadId: string
  subject: string
  lastPreview: string | null
  lastAt: string | null
  messageCount: number
}

// Matter-scoped communication history from the substrate (works offline from
// Gmail — this is the ingested record).
export async function matterCommunications(
  ctx: ActionContext,
  matterEntityId: string,
): Promise<MatterCommunication[]> {
  return withActionContext(ctx, async (client) => {
    const res = await client.query<{
      id: string
      subject: string | null
      last_preview: string | null
      last_at: string | null
      n: string
    }>(
      `SELECT t.id, t.subject,
              (SELECT m.body_preview FROM communication_message m
                WHERE m.tenant_id = t.tenant_id AND m.thread_id = t.id
                ORDER BY m.occurred_at DESC LIMIT 1) AS last_preview,
              (SELECT to_char(max(m.occurred_at), 'YYYY-MM-DD"T"HH24:MI:SSTZH:TZM')
                 FROM communication_message m
                WHERE m.tenant_id = t.tenant_id AND m.thread_id = t.id) AS last_at,
              (SELECT count(*) FROM communication_message m
                WHERE m.tenant_id = t.tenant_id AND m.thread_id = t.id) AS n
       FROM communication_thread t
       WHERE t.tenant_id = $1 AND $2::uuid = ANY(t.related_entity_ids)
       ORDER BY last_at DESC NULLS LAST`,
      [ctx.tenantId, matterEntityId],
    )
    return res.rows.map((r) => ({
      threadId: r.id,
      subject: r.subject ?? '(no subject)',
      lastPreview: r.last_preview,
      lastAt: r.last_at,
      messageCount: Number(r.n),
    }))
  })
}

export interface MatterMessageBody {
  threadId: string
  subject: string
  direction: 'inbound' | 'outbound' | null
  from: string | null
  to: string | null
  sentAt: string | null
  body: string
  // True when the stored body was longer than the per-message cap and got cut.
  truncated: boolean
}

// Full message BODIES for a matter's threads, newest-first — for grounding the
// in-app assistant (matterCommunications gives only subjects + a 280-char
// preview). JOINs the stored full body (content_blob.body via body_blob_id) so
// the model can read what was actually said. Capped on BOTH message count and
// per-body length here so a caller can never pull megabytes into a prompt; falls
// back to the preview when a message has no stored blob. Tenant-scoped via
// withActionContext (RLS). The bodies are CLIENT-AUTHORED / untrusted — callers
// that put them in a prompt must delimit them as data (see assistantContext.ts).
export async function matterCommunicationBodies(
  ctx: ActionContext,
  matterEntityId: string,
  opts: { maxMessages?: number; maxBodyChars?: number } = {},
): Promise<MatterMessageBody[]> {
  const maxMessages = Math.max(1, Math.min(opts.maxMessages ?? 8, 50))
  const maxBodyChars = Math.max(200, Math.min(opts.maxBodyChars ?? 2000, 20000))
  return withActionContext(ctx, async (client) => {
    const res = await client.query<{
      thread_id: string
      subject: string | null
      direction: string | null
      sender: string | null
      recipient: string | null
      occurred_at: string | null
      body: string | null
      truncated: boolean
    }>(
      `SELECT t.id AS thread_id, t.subject,
              m.payload->>'direction' AS direction,
              m.payload->>'from' AS sender,
              m.payload->>'to' AS recipient,
              to_char(m.occurred_at, 'YYYY-MM-DD"T"HH24:MI:SSTZH:TZM') AS occurred_at,
              left(COALESCE(b.body, m.body_preview, ''), $3) AS body,
              (length(COALESCE(b.body, m.body_preview, '')) > $3) AS truncated
         FROM communication_thread t
         JOIN communication_message m ON m.tenant_id = t.tenant_id AND m.thread_id = t.id
         LEFT JOIN content_blob b ON b.id = m.body_blob_id
        WHERE t.tenant_id = $1 AND $2::uuid = ANY(t.related_entity_ids)
        ORDER BY m.occurred_at DESC
        LIMIT $4`,
      [ctx.tenantId, matterEntityId, maxBodyChars, maxMessages],
    )
    return res.rows.map((r) => ({
      threadId: r.thread_id,
      subject: r.subject ?? '(no subject)',
      direction: (r.direction as 'inbound' | 'outbound' | null) ?? null,
      from: r.sender,
      to: r.recipient,
      sentAt: r.occurred_at,
      body: r.body ?? '',
      truncated: r.truncated ?? false,
    }))
  })
}
