'use client'

// Brief engine WP2/WP3 — the Brief window (design: docs/design/briefs/
// DESIGN.md §6), on the shared li-modal chrome (size wide). `scope` picks the
// matter or client target and the matching MCP tool pair + copy; everything
// else (get-on-open, generate-on-click-only, stale/refresh, rendered markdown)
// is shared. The contract the founder decided (decision 1) is enforced here in
// the small print:
//
//   - Opening the modal calls *.brief.get ONLY — a pure read. No brief is ever
//     generated by opening a window.
//   - Generation happens on an explicit click: "Generate brief" (first run) or
//     the amber "Out of date — Refresh" affordance (stale). Never automatic.
//
// Against a database where the brief kinds are not yet seeded, `get` returns
// { brief: null } and the modal shows the honest first-run state.
//
// Client Brief only: the persisted `research` record (api/briefResearchGuard.ts)
// is rendered as an audit strip — every outbound query string, verbatim, so an
// attorney can see exactly what left the firm — or an honest "research not run"
// line when Perplexity isn't connected / nothing was researchable. Never an error.
import { useEffect, useState } from 'react'
import { callAttorneyMcp } from '@/lib/mcpAttorney'
import { Modal } from '@/components/Modal'
import { GemSparkle } from '@/components/GemSparkle'
import { renderMarkdown } from '@/lib/draftExport'
import { formatDateTime } from '@/lib/datetime'
import { RefreshIcon, SearchIcon } from '@/components/icons'

export type BriefScope =
  | { kind: 'matter'; matterEntityId: string }
  | { kind: 'client'; clientEntityId: string }

interface BriefSection {
  heading: string
  body: string
  confidence: number
  sourceRefs: string[]
  quoted: boolean
}

interface BriefResearchQuery {
  query: string
  kind: 'business' | 'person'
}

interface BriefResearchRecord {
  ranAt: string
  connected: boolean
  skippedReason: string | null
  queries: BriefResearchQuery[]
  findings: Array<{
    query: string
    kind: 'business' | 'person'
    answer: string
    citations: string[]
  }>
}

export interface BriefView {
  briefEntityId: string
  briefType: string
  markdown: string
  sections: BriefSection[]
  generatedAt: string | null
  modelIdentity: string | null
  confidence: number | null
  sourceWatermark: string | null
  // Client Brief only.
  research?: BriefResearchRecord | null
}

export interface BriefReadResult {
  brief: BriefView | null
  stale: boolean
  watermark: string | null
}

// B2.2 (MATTER-BRIEF-BACKGROUND-1): the Matter Brief's generate now runs on the
// worker, not in this modal's own request — BriefButton owns the enqueue+poll
// (so it survives the modal being closed) and hands this shape down. When
// present, this modal is a presentational view over it instead of managing its
// own get/generate. Client Brief never passes this — its generate stays the
// original synchronous in-modal call, unchanged.
export interface MatterBriefController {
  state: BriefReadResult | null
  generating: boolean
  error: string | null
  // True for a short window right after a background generation lands — the
  // one-time completion pulse (BriefButton clears it after PULSE_MS).
  justCompleted: boolean
  onGenerate: (force: boolean) => void
}

const TOOL_NAMES: Record<BriefScope['kind'], { get: string; generate: string }> = {
  matter: { get: 'legal.matter.brief.get', generate: 'legal.matter.brief.generate' },
  client: { get: 'legal.client.brief.get', generate: 'legal.client.brief.generate' },
}

function scopeInput(scope: BriefScope): Record<string, string> {
  return scope.kind === 'matter'
    ? { matterEntityId: scope.matterEntityId }
    : { clientEntityId: scope.clientEntityId }
}

function ResearchStrip({ research }: { research: BriefResearchRecord }) {
  if (!research.connected) {
    return (
      <div className="li-brief-research li-brief-research-skipped">
        <SearchIcon size={13} />
        <span>
          External research: not run{research.skippedReason ? ` — ${research.skippedReason}` : ''}.
        </span>
      </div>
    )
  }
  return (
    <details className="li-brief-research">
      <summary>
        <SearchIcon size={13} />
        External research ran ({research.queries.length} quick{' '}
        {research.queries.length === 1 ? 'query' : 'queries'} to Perplexity,{' '}
        {formatDateTime(research.ranAt)}) — click to see exactly what left the firm
      </summary>
      <ul className="li-brief-research-queries">
        {research.queries.map((q, i) => (
          <li key={i} className="li-brief-research-query">
            <span className="li-brief-research-kind">{q.kind}</span>
            {q.query}
          </li>
        ))}
      </ul>
    </details>
  )
}

export function BriefModal({
  scope,
  onClose,
  matterController,
}: {
  scope: BriefScope
  onClose: () => void
  matterController?: MatterBriefController
}) {
  // null = the initial get is still in flight. Unused when matterController is
  // present — the button already owns this read.
  const [localState, setLocalState] = useState<BriefReadResult | null>(null)
  const [localGenerating, setLocalGenerating] = useState(false)
  const [localError, setLocalError] = useState<string | null>(null)
  const tools = TOOL_NAMES[scope.kind]
  const title = scope.kind === 'matter' ? 'Matter Brief' : 'Client Brief'
  const noun = scope.kind === 'matter' ? 'matter' : 'client'
  // scope's real identity, as two stable primitives — used as the effect's
  // dependency list directly (no JSON.stringify indirection needed).
  const targetId = scope.kind === 'matter' ? scope.matterEntityId : scope.clientEntityId

  useEffect(() => {
    if (matterController) return // the button already owns this read (B2.2)
    let cancelled = false
    callAttorneyMcp<BriefReadResult>({
      toolName: tools.get,
      input: scopeInput(scope),
    })
      .then((r) => {
        if (!cancelled) setLocalState(r)
      })
      .catch((e) => {
        if (!cancelled) setLocalError(e instanceof Error ? e.message : String(e))
      })
    return () => {
      cancelled = true
    }
  }, [scope.kind, targetId, tools.get, matterController])

  async function generate(force: boolean) {
    if (matterController) {
      // Matter scope (B2.2): the button enqueues on the worker and polls —
      // this modal just asked it to start (or restart) that.
      matterController.onGenerate(force)
      return
    }
    if (localGenerating) return
    setLocalGenerating(true)
    setLocalError(null)
    try {
      const r = await callAttorneyMcp<BriefReadResult>({
        toolName: tools.generate,
        input: force ? { ...scopeInput(scope), force: true } : scopeInput(scope),
      })
      setLocalState(r)
    } catch (e) {
      setLocalError(e instanceof Error ? e.message : String(e))
    } finally {
      setLocalGenerating(false)
    }
  }

  const state = matterController ? matterController.state : localState
  const generating = matterController ? matterController.generating : localGenerating
  const error = matterController ? matterController.error : localError
  const brief = state?.brief ?? null

  return (
    <Modal title={title} onClose={onClose} size="wide">
      {error && <div className="li-modal-alert">{error}</div>}

      {generating ? (
        <div className="li-brief-working">
          <GemSparkle size={22} />
          <div>
            <div className="li-brief-working-title">Synthesizing the {noun} brief…</div>
            <div className="li-brief-working-sub">
              {scope.kind === 'matter'
                ? 'Reading the matter’s history, communications, documents, notes, and billing, then writing the brief. This takes a moment — running on the worker, so it is safe to close this window and come back.'
                : 'Reading the client’s profile, every matter, notes, transcripts, and messages — plus a quick, privacy-guarded external search — then writing the brief. This takes a moment.'}
            </div>
          </div>
        </div>
      ) : state === null && !error ? (
        <p className="li-brief-loading">
          <span className="spinner" /> Checking for a brief…
        </p>
      ) : brief === null ? (
        <div className="li-brief-empty">
          <p className="li-brief-empty-lead">No brief yet for this {noun}.</p>
          <p className="li-brief-empty-sub">
            {scope.kind === 'matter'
              ? 'Generate one to get a synthesized narrative of everything on the matter — status, commitments, deadlines, communications, and open items — with honest flags for anything the record does not answer.'
              : 'Generate one to get a synthesized narrative of this client — every matter, status, commitments, and open items — with a quick external check on the business (and its primary contact) where one is warranted, and honest flags for anything the record does not answer.'}
          </p>
          <button
            type="button"
            className="li-brief-generate-btn"
            onClick={() => void generate(false)}
          >
            <GemSparkle size={16} />
            Generate Brief
          </button>
        </div>
      ) : (
        <div className="li-brief-view">
          <div className={state?.stale ? 'li-brief-stale' : 'li-brief-toprow li-brief-fresh'}>
            <span>
              {state?.stale
                ? `Out of date — the ${noun} has activity newer than this brief${
                    brief.generatedAt ? ` (generated ${formatDateTime(brief.generatedAt)})` : ''
                  }.`
                : `Last Generated ${brief.generatedAt ? formatDateTime(brief.generatedAt) : '—'}.`}
            </span>
            <button
              type="button"
              className={
                state?.stale
                  ? 'li-brief-refresh-btn'
                  : 'li-brief-refresh-btn li-brief-refresh-btn--quiet'
              }
              onClick={() => void generate(true)}
              disabled={generating}
            >
              <RefreshIcon size={14} />
              Refresh Brief
            </button>
          </div>
          {matterController?.justCompleted && (
            <div className="li-brief-updated-flash">Brief updated.</div>
          )}
          {(brief.modelIdentity || typeof brief.confidence === 'number') && (
            <div className="li-brief-meta">
              {brief.modelIdentity ?? ''}
              {typeof brief.confidence === 'number'
                ? `${brief.modelIdentity ? ' · ' : ''}confidence ${Math.round(brief.confidence * 100)}%`
                : ''}
            </div>
          )}
          {brief.research && <ResearchStrip research={brief.research} />}
          <div
            className="li-brief-body"
            // renderMarkdown escapes ALL inline HTML (the assistant-chat
            // renderer) — model output is never injected raw.
            dangerouslySetInnerHTML={{ __html: renderMarkdown(brief.markdown) }}
          />
        </div>
      )}
    </Modal>
  )
}
