// WP2.4 acceptance receipt — non-destructive. Creates a throwaway service, saves
// a Contract-I questionnaire THROUGH THE CORE (the same updateQuestionnaire path
// the builder uses), reads the persisted schema back, asserts the shape
// (autogenerated ids + required + allow_unknown + ask_attorney, and NO help /
// description keys), then retires the throwaway service so nothing lingers.
//
// Run:  tsx --env-file=.env.local verticals/legal/demo/verify-questionnaire-shape.ts
import { closeDbPool } from '@exsto/shared'
import { createService, updateQuestionnaire, getQuestionnaire, retireService } from '@exsto/legal'
import type { ActionContext } from '@exsto/substrate'
import '@exsto/legal' // register legal action handlers

const TENANT_ID = '00000000-0000-0000-0000-000000000001'
const SYSTEM_ACTOR_ID = '00000000-0000-0000-0001-000000000001'
const ctx: ActionContext = { tenantId: TENANT_ID, actorId: SYSTEM_ACTOR_ID }

// Mirror the builder's client-side id autogen (editorToWire → slugify): the id is
// derived from the label, never typed by a human.
function slugify(s: string): string {
  return s
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 60)
}

async function main() {
  const svc = await createService(ctx, {
    displayName: 'WP2.4 questionnaire shape check',
    route: 'manual',
  })
  const serviceKey = svc.serviceKey
  console.log('created throwaway service:', serviceKey)

  // Exactly what the builder emits: ids autogenerated from labels, the three
  // humane flags, no `help` on any field, no `description` on the form.
  const schema = {
    id: serviceKey,
    version: 1,
    title: 'Shape check intake',
    jurisdiction: 'NC',
    sections: [
      {
        id: slugify('About the company'),
        title: 'About the company',
        fields: [
          {
            id: slugify('Proposed LLC name'),
            label: 'Proposed LLC name',
            type: 'text',
            required: true,
            allow_unknown: true,
            ask_attorney: true,
          },
          {
            id: slugify('Management structure'),
            label: 'Management structure',
            type: 'select',
            options: ['member_managed', 'manager_managed'],
          },
        ],
      },
    ],
  }

  await updateQuestionnaire(ctx, serviceKey, schema)
  const saved = await getQuestionnaire(ctx, serviceKey)
  if (!saved) throw new Error('questionnaire missing after save')

  const json = JSON.stringify(saved)
  const f0 = saved.sections[0].fields[0] as Record<string, unknown>
  const checks = {
    field0_id_from_label: f0.id === 'proposed_llc_name',
    field0_required: f0.required === true,
    field0_allow_unknown: f0.allow_unknown === true,
    field0_ask_attorney: f0.ask_attorney === true,
    no_help_key_anywhere: !json.includes('"help"'),
    no_description_key: !('description' in saved),
  }
  console.log('persisted field[0]:', JSON.stringify(f0))
  console.log('checks:', JSON.stringify(checks, null, 2))
  const allPass = Object.values(checks).every(Boolean)
  console.log(allPass ? 'PASS — Contract-I shape persisted through the core.' : 'FAIL')

  await retireService(ctx, serviceKey)
  console.log('retired throwaway service:', serviceKey)
  await closeDbPool()
  if (!allPass) process.exitCode = 1
}

main().catch((err) => {
  console.error(err)
  process.exitCode = 1
})
